#!/bin/sh
# Clear the terminal screen
clear

# Check if the input parameter is provided
if [ -z "$1" ]; then
echo "Usage: $0 <path_to_file_or_directory>"
exit 1
fi
input_path=$1
# If the input path contains a file extension, process the file
if [[ "$input_path" =~ \.[a-zA-Z0-9]+$ ]]; then
input_file="$input_path"
output_path="${input_path%.*}.hack"
# Call the Python script to process the file
python3 Main.py "$input_file" > "$output_path"
# If the input path represents a directory, process all .asm files in the directory
elif [[ -d "$input_path" ]]; then
for file in "$input_path"/*.asm; do
input_file="$file"
output_path="${file%.asm}.hack"
# Call the Python script to process the file
python3 Main.py "$input_file" > "$output_path"
done
else
echo "Invalid input path. Please provide a valid path to a .asm file or directory."
fi
